Update the component layout and enable concurrent run to improve performance
COSIMA/MOM6-CICE6 pull request #101
Opened 2024-08-21 05:50 UTC by minghangli-uni

See https://github.com/COSIMA/access-om3/issues/130#issuecomment-2301146030

2024-08-21 10:35 UTC, dougiesquire requested changes
`ocn_rootpe` needs to be modified as per my suggestion below.

Also the `config.yaml` needs to be changed as in [my original comment](https://github.com/COSIMA/access-om3/issues/130#issuecomment-2301146030)

2024-08-21 10:35 UTC, dougiesquire commented on nuopc.runconfig
>       ocn_rootpe = 0
```suggestion
     ocn_rootpe = 24
```

2024-08-22 05:10 UTC, dougiesquire commented on nuopc.runseq
> +@3600
I don't understand why this change is here after rebasing? Would you like me to rebase this branch on `1deg_jra55do_ryf`?

2024-08-22 06:06 UTC, dougiesquire requested changes
Still not quite right. e12a794a2bfda41173fd101acd47d4d52681a403 should not be in this PR since it's already included in `1deg_jra55do_ryf`.

To rebase you need to:
```
git checkout 1deg_jra55do_ryf
git pull
git checkout 1deg_jra55do_ryf.iss130
git rebase 1deg_jra55do_ryf
```

2024-08-22 06:24 UTC, minghangli-uni commented
I forgot https://github.com/COSIMA/MOM6-CICE6/commit/e12a794a2bfda41173fd101acd47d4d52681a403 was merged. Now it should be right.

2024-08-22 06:57 UTC, dougiesquire approved these changes
Thanks @minghangli-uni. LGTM

2024-08-22 06:59 UTC, merged

2024-08-23 01:06 UTC, minghangli-uni commented
!cherry-pick f3d4e7d into 1deg_jra55do_iaf 1deg_jra55do_ryf_wombatlite